import speech_recognition as sr
import pyttsx3

capitals = {
    # all countries capitals
    "afghanistan": "Kabul",
    "albania": "Tirana",
    "andhra pradesh":"Amaravathi",
    "algeria": "Algiers",
    "andorra": "Andorra la Vella",
    "angola": "Luanda",
    "antigua and barbuda": "St. John's",
    "argentina": "Buenos Aires",
    "armenia": "Yerevan",
    "australia": "Canberra",
    "austria": "Vienna",
    "azerbaijan": "Baku",
    "bahamas": "Nassau",
    "bahrain": "Manama",
    "bangladesh": "Dhaka",
    "barbados": "Bridgetown",
    "belarus": "Minsk",
    "belgium": "Brussels",
    "belize": "Belmopan",
    "benin": "Porto-Novo",
    "bhutan": "Thimphu",
    "bolivia": "Sucre",
    "bosnia and herzegovina": "Sarajevo",
    "botswana": "Gaborone",
    "brazil": "Brasília",
    "brunei": "Bandar Seri Begawan",
    "bulgaria": "Sofia",
    "burkina faso": "Ouagadougou",
    "burundi": "Bujumbura",
    "cambodia": "Phnom Penh",
    "cameroon": "Yaoundé",
    "canada": "Ottawa",
    "cape verde": "Praia",
    "central african republic": "Bangui",
    "chad": "N'Djamena",
    "chile": "Santiago",
    "china": "Beijing",
    "colombia": "Bogotá",
    "comoros": "Moroni",
    "congo": "Kinshasa",
    "costa rica": "San José",
    "croatia": "Zagreb",
    "cuba": "Havana",
    "cyprus": "Nicosia",
    "czech republic": "Prague",
    "denmark": "Copenhagen",
    "djibouti": "Djibouti",
    "dominica": "Roseau",
    "dominican republic": "Santo Domingo",
    "east timor": "Dili",
    "ecuador": "Quito",
    "egypt": "Cairo",
    "el salvador": "San Salvador",
    "equatorial guinea": "Malabo",
    "eritrea": "Asmara",
    "estonia": "Tallinn",
    "ethiopia": "Addis Ababa",
    "fiji": "Suva",
    "finland": "Helsinki",
    "france": "Paris",
    "gabon": "Libreville",
    "gambia": "Banjul",
    "georgia": "Tbilisi",
    "germany": "Berlin",
    "ghana": "Accra",
    "greece": "Athens",
    "grenada": "St. George's",
    "guatemala": "Guatemala City",
    "guinea": "Conakry",
    "guinea-bissau": "Bissau",
    "guyana": "Georgetown",
    "haiti": "Port-au-Prince",
    "honduras": "Tegucigalpa",
    "hungary": "Budapest",
    "iceland": "Reykjavík",
    "india": "New Delhi",
    "indonesia": "Jakarta",
    "iran": "Tehran",
    "iraq": "Baghdad",
    "ireland": "Dublin",
    "israel": "Jerusalem",
    "italy": "Rome",
    "jamaica": "Kingston",
    "japan": "Tokyo",
    "jordan": "Amman",
    "kazakhstan": "Astana",
    "kenya": "Nairobi",
    "kiribati": "Tarawa",
    "north korea": "Pyongyang",
    "south korea": "Seoul",
    "kosovo": "Pristina",
    "kuwait": "Kuwait City",
    "kyrgyzstan": "Bishkek",
    "laos": "Vientiane",
    "latvia": "Riga",
    "lebanon": "Beirut",
    "lesotho": "Maseru",
    "liberia": "Monrovia",
    "libya": "Tripoli",
    "liechtenstein": "Vaduz",
    "lithuania": "Vilnius",
    "luxembourg": "Luxembourg",
    "macedonia": "Skopje",
    "madagascar": "Antananarivo",
    "malawi": "Lilongwe",
    "malaysia": "Kuala Lumpur",
    "maldives": "Malé",
    "mali": "Bamako",
    "malta": "Valletta",
    "marshall islands": "Majuro",
    "mauritania": "Nouakchott",
    "mauritius": "Port Louis",
    "mexico": "Mexico City",
    "micronesia": "Palikir",
    "moldova": "Chișinău",
    "monaco": "Monaco",
    "mongolia": "Ulaanbaatar",
    "montenegro": "Podgorica",
    "morocco": "Rabat",
    "mozambique": "Maputo",
    "myanmar": "Naypyidaw",
    "namibia": "Windhoek",
    "nauru": "Yaren",
    "nepal": "Kathmandu",
    "netherlands": "Amsterdam",
    "new zealand": "Wellington",
    "nicaragua": "Managua",
    "niger": "Niamey",
    "nigeria": "Abuja",
    "norway": "Oslo",
    "oman": "Muscat",
    "pakistan": "Islamabad",
    "palau": "Ngerulmud",
    "panama": "Panama City",
    "papua new guinea": "Port Moresby",
    "paraguay": "Asunción",
    "peru": "Lima",
    "philippines": "Manila",
    "poland": "Warsaw",
    "portugal": "Lisbon",
    "qatar": "Doha",
    "romania": "Bucharest",
    "russia": "Moscow",
    "rwanda": "Kigali",
    "st. kitts and nevis": "Basseterre",
    "st. lucia": "Castries",
    "st. vincent and the grenadines": "Kingstown",
    "samoa": "Apia",
    "san marino": "San Marino",
    "sao tome and principe": "São Tomé",
    "saudi arabia": "Riyadh",
    "senegal": "Dakar",
    "serbia": "Belgrade",
    "seychelles": "Victoria",
    "sierra leone": "Freetown",
    "singapore": "Singapore",
    "slovakia": "Bratislava",
    "slovenia": "Ljubljana",
    "solomon islands": "Honiara",
    "somalia": "Mogadishu",
    "south africa": "Pretoria",
    "south sudan": "Juba",
    "spain": "Madrid",
    "sri lanka": "Sri Jayawardenepura Kotte",
    "sudan": "Khartoum",
    "suriname": "Paramaribo",
    "swaziland": "Mbabane",
    "sweden": "Stockholm",
    "switzerland": "Bern",
    "syria": "Damascus",
    "taiwan": "Taipei",
    "tajikistan": "Dushanbe",
    "tanzania": "Dodoma",
    "thailand": "Bangkok",
    "togo": "Lomé",
    "tonga": "Nukuʻalofa",
    "trinidad and tobago": "Port of Spain",
    "tunisia": "Tunis",
    "turkey": "Ankara",
    "turkmenistan": "Ashgabat",
    "tuvalu": "Funafuti",
    "uganda": "Kampala",
    "ukraine": "Kyiv",
    "united arab emirates": "Abu Dhabi",
    "united kingdom": "London",
    "united states": "Washington, D.C.",
    "uruguay": "Montevideo",
    "uzbekistan": "Tashkent",
    "vanuatu": "Port Vila",
    "vatican city": "Vatican City",
    "venezuela": "Caracas",
    "vietnam": "Hanoi",
    "yemen": "Sana'a",
    "zambia": "Lusaka",
    "zimbabwe": "Harare"
}
def check_capital(city):
    for country, capital in capitals.items():
        if city.lower() == capital.lower():
            return True
    return False
